# Generated by Django 2.2.5 on 2020-02-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_tag_image'),
    ]

    operations = [
    ]
